version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: fio
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      COMPOSER_MEMORY_LIMIT: -1
      PHP_IDE_CONFIG: serverName=fio
    networks:
      - fio
    stdin_open: true
  dbm:
    image: mariadb:10.5
    environment:
      MYSQL_DATABASE: fio
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret
    volumes:
      - ./.docker/mysqldump:/docker-mysqldump
    networks:
      - fio
  logs_dbm:
    image: mariadb:10.5
    environment:
      MYSQL_DATABASE: fio_logs
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret
    networks:
      - fio
  nginx:
    image: nginx:1.19
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./.docker/nginx:/etc/nginx/conf.d/
    networks:
      - fio
  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - fio
  adminer:
    image: adminer
    restart: always
    ports:
      - 3000:8080
    networks:
      - fio
networks:
  fio:
    driver: bridge
